/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:56c82925-ccc9-4bc8-9270-b514f158cf8a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_0cn7mgIjl",
    "aws_user_pools_web_client_id": "1g30en1fg92cj8maa0mofmnuat",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ofa3x5mtd5akzmw3gxerxqghnu.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
